# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  gh-pages: sugarshin/gh-pages@0.0.6
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo apt install aspell
      - run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: ./test.sh
      - run: php generate.php

      - store_artifacts:
          path: generated
      - run:
          name: Display link to built website
          command: |
            echo "Generated website available at:"
            echo https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}/artifacts/0/generated/01-introduction.html
      - persist_to_workspace:
          root: ~/
          paths: project/generated

  deploy_ghpages:
    steps:
      - gh-pages/deploy:
          ssh-fingerprints: '73:52:89:88:54:e7:4b:5a:c1:25:9b:db:85:d7:fc:a3'
          attach-workspace: true
          build-dir: project/generated
workflows:
  Workflow:
    jobs:
      - build
      - deploy_ghpages:
          requires:
            - build
